# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_auto_20180610_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_url',
            field=models.CharField(default='https://auto.ferrari.com/en_EN/wp-content/uploads/sites/5/2014/06/ferrari-458-speciale-header-v4.jpg', max_length=200),
        ),
    ]
