# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 05:53
from __future__ import unicode_literals

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_auto_20180709_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='imagee',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
